---
- name: add repository
  template: src=mongodb-org.repo.j2 dest=/etc/yum.repos.d/mongodb-org.repo
  tags:
    - mongodb

- name: install package
  yum: name=mongodb-org state=present
  tags:
    - mongodb

- name: adjust mongod configuration
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify:
    - restart mongodb
  tags:
    - mongodb

- name: setup as startup service
  service: name=mongod state=started enabled=yes
  tags:
    - mongodb
