---
- name: add repository
  template: src=mongodb-org.repo.j2 dest=/etc/yum.repos.d/mongodb-org.repo
  tags:
    - mongodb

- name: install package
  yum: name=mongodb-org state=present
  tags:
    - mongodb

- name: copy standalone and repl configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - src: mongod.repl.conf.j2
    dest: /opt/mongod.repl.conf
  - src: mongod.standalone.conf.j2
    dest: /opt/mongod.standalone.conf
  tags:
  - mongodb

- name: copy mongo startup with backup script
  template:
    src: start_mongo_with_backup.sh
    dest: /opt/start_mongo_with_backup.sh
    mode: u=rx,g=r,o=r
  tags:
  - mongodb

- name: backup mongod.conf
  command: cp -a /etc/mongod.conf /etc/mongod.conf.bak
  tags:
  - mongodb

- name: remove previous config incase of it being not a symlink
  file:
    dest: /etc/mongod.conf
    state: absent

- name: setup symbolic link to standalone mongo config
  file:
    src: /opt/mongod.standalone.conf
    dest: /etc/mongod.conf
    state: link
  notify:
  - restart mongodb
  tags:
  - mongodb

- name: setup as startup service
  service: name=mongod state=started enabled=yes
  tags:
    - mongodb
